import type { Locacion2026 } from "./locaciones2026.types";

export const LOCACIONES_2026: Locacion2026[] = [
  // ========= USPALLATA (10) =========
  {
    id: "uspallata-foyer",
    sede: "USPALLATA",
    nombre: "Foyer",
    ubicacion: "Uspallata 3160, CABA",
    capacidad: 100,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    notas: "Cuenta con cocheras de cortesía",
  },
  {
    id: "uspallata-auditorio",
    sede: "USPALLATA",
    nombre: "Auditorio",
    ubicacion: "Uspallata 3160, CABA",
    capacidad: 312,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "pantalla, proyector y sonido",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    escenario: true,
    notas: "Escenario con accesibilidad",
  },
  {
    id: "uspallata-sala-gabinete",
    sede: "USPALLATA",
    nombre: "Sala de Gabinete",
    ubicacion: "Uspallata 3160, CABA",
    capacidad: 37,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "pantalla televisor",
    mobiliario: true,
    backstage: false,
    estacionamiento: true,
    wifi: false,
    notas: "Cuenta con cochera de cortesía",
  },
  {
    id: "uspallata-espacio-contiguo-sala-gabinete",
    sede: "USPALLATA",
    nombre: "Espacio contiguo Sala Gabinete",
    ubicacion: "Uspallata 3160, CABA",
    capacidad: null,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: true,
    wifi: false,
    notas: "Ideal para realizar entrevistas. Mobiliario: sillones de 1 cuerpo y 2 cuerpos y mesas ratonas. Cuenta con cochera de cortesía",
  },
  {
    id: "uspallata-sala-1",
    sede: "USPALLATA",
    nombre: "Sala 1",
    ubicacion: "Uspallata 3160, CABA",
    capacidad: 25,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Solo televisor",
    mobiliario: true,
    backstage: false,
    estacionamiento: true,
    wifi: false,
    notas: "Cuenta con cochera de cortesía",
  },
  {
    id: "uspallata-sala-2",
    sede: "USPALLATA",
    nombre: "Sala 2",
    ubicacion: "Uspallata 3160, CABA",
    capacidad: 16,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Solo televisor",
    mobiliario: true,
    backstage: false,
    estacionamiento: true,
    wifi: false,
    contacto: "Intendencia Uspallata intendenciacdg@buenosaires.gob.ar",
    notas: "Cuenta con cochera de cortesía",
  },
  {
    id: "uspallata-sala-3",
    sede: "USPALLATA",
    nombre: "Sala 3",
    ubicacion: "Uspallata 3160, CABA",
    capacidad: 12,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Solo televisor",
    mobiliario: true,
    backstage: false,
    estacionamiento: true,
    wifi: false,
    contacto: "Intendencia Uspallata intendenciacdg@buenosaires.gob.ar",
    notas: "Cuenta con cochera de cortesía",
  },
  {
    id: "uspallata-sala-4",
    sede: "USPALLATA",
    nombre: "Sala 4",
    ubicacion: "Uspallata 3160, CABA",
    capacidad: 16,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Solo televisor",
    mobiliario: true,
    backstage: false,
    estacionamiento: true,
    wifi: false,
    contacto: "Intendencia Uspallata intendenciacdg@buenosaires.gob.ar",
    notas: "Cuenta con cochera de cortesía",
  },
  {
    id: "uspallata-sala-5",
    sede: "USPALLATA",
    nombre: "Sala 5",
    ubicacion: "Uspallata 3160, CABA",
    capacidad: 12,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Solo televisor",
    mobiliario: true,
    backstage: false,
    estacionamiento: true,
    wifi: false,
    contacto: "Intendencia Uspallata intendenciacdg@buenosaires.gob.ar",
    notas: "Cuenta con cochera de cortesía",
  },
  {
    id: "uspallata-sala-mil",
    sede: "USPALLATA",
    nombre: "Sala Mil",
    ubicacion: "Uspallata 3160, CABA",
    capacidad: 50,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantalla",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    notas: "Mesas y sillas: 20 sillas grises + 30 sillas blancas extras. Cochera de cortesía",
  },

  // ========= PALACIO LEZAMA (2) =========
  {
    id: "palacio-lezama-auditorio",
    sede: "Palacio Lezama",
    nombre: "Auditorio",
    ubicacion: "Av. Martín García 344, CABA",
    capacidad: 200,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    notas: "Entrada por calle Pilcomayo",
  },
  {
    id: "palacio-lezama-salas-reunion",
    sede: "Palacio Lezama",
    nombre: "Salas de Reunión",
    ubicacion: "Av. Martín García 344, CABA",
    capacidad: 50,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: true,
    wifi: false,
    notas: "Ascensor. Son dos salas iguales, una al lado de la otra. Entrada por calle Pilcomayo",
  },

  // ========= ECOPARQUE (3) =========
  {
    id: "ecoparque-salon-indostanico",
    sede: "Ecoparque",
    nombre: "Salón Indostánico",
    ubicacion: "República Árabe Síria 3000, CABA",
    capacidad: 45,
    accesibilidad: false,
    tecnica: true,
    tecnicaDetalle: "Solo televisor",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    notas: "Está en un primer piso. Solo se accede con escalera. Contiene salas de reuniones en planta baja. Baños a una cuadra de distancia. Backstage: cocina",
  },
  {
    id: "ecoparque-glorieta",
    sede: "Ecoparque",
    nombre: "Glorieta",
    ubicacion: "República Árabe Síria 3000, CABA",
    capacidad: 40,
    accesibilidad: false,
    tecnica: false,
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    notas: "No se puede conectar ningún tipo de instrumento eléctrico ni cables. Mobiliario: bancos de plaza",
  },
  {
    id: "ecoparque-antiguo-comedor",
    sede: "Ecoparque",
    nombre: "Antiguo Comedor",
    ubicacion: "Ingreso por Plaza Italia (entrada pública)",
    capacidad: 40,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
    notas: "Baño a 50 mts",
  },

  // ========= TEATRO COLÓN / COLÓN FÁBRICA (3) =========
  {
    id: "teatro-colon-salon-dorado",
    sede: "Teatro Colón",
    nombre: "Salón Dorado",
    ubicacion: "Cerrito 628 (Acreditación) | Tucumán 1157 (Ingreso proveedores)",
    capacidad: 200,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
    notas: "Cuenta con foyer para catering. Mobiliario: 130 sillas",
  },
  {
    id: "teatro-colon-sala-principal",
    sede: "Teatro Colón",
    nombre: "Sala Principal",
    ubicacion: "Cerrito 628 (Acreditación) | Tucumán 1157 (Ingreso proveedores)",
    capacidad: 200,
    accesibilidad: true,
    tecnica: true,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: butacas",
  },
  {
    id: "colon-fabrica",
    sede: "Colón Fábrica",
    nombre: "Colón Fábrica",
    ubicacion: "Av. Pedro de Mendoza 2163, CABA",
    capacidad: 60,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Televisor",
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
  },

  // ========= CCR (7) =========
  {
    id: "ccr-microcine",
    sede: "Centro Cultural Recoleta",
    nombre: "Microcine",
    ubicacion: "Junín 1930, CABA",
    capacidad: 100,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Solo pantalla",
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: butacas",
  },
  {
    id: "ccr-capilla",
    sede: "Centro Cultural Recoleta",
    nombre: "Capilla",
    ubicacion: "Junín 1930, CABA",
    capacidad: 116,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantalla y sonido",
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: butacas",
  },
  {
    id: "ccr-patio-aljibe",
    sede: "Centro Cultural Recoleta",
    nombre: "Patio del Aljibe",
    ubicacion: "Junín 1930, CABA",
    capacidad: 200,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
  },
  {
    id: "ccr-patio-naranjos",
    sede: "Centro Cultural Recoleta",
    nombre: "Patio de los Naranjos",
    ubicacion: "Junín 1930, CABA",
    capacidad: 30,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: sillas tipo reposera",
  },
  {
    id: "ccr-sala-c",
    sede: "Centro Cultural Recoleta",
    nombre: "Sala C",
    ubicacion: "Junín 1930, CABA",
    capacidad: 30,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Solo televisor",
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    notas: "Se encuentra en el primer piso y se puede acceder por ascensor",
  },
  {
    id: "ccr-villa-villa",
    sede: "Centro Cultural Recoleta",
    nombre: "Villa Villa",
    ubicacion: "Junín 1930, CABA",
    capacidad: 250,
    accesibilidad: true,
    tecnica: false,
    mobiliario: false,
    backstage: true,
    estacionamiento: false,
    wifi: false,
  },

  // ========= USINA DEL ARTE (5) =========
  {
    id: "usina-foyer",
    sede: "Usina del Arte",
    nombre: "Foyer",
    ubicacion: "Agustín F. Caffarena 1, CABA (Se acredita en Caffarena 29)",
    capacidad: 500,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    notas: "Estacionamiento en Caffarena 39",
  },
  {
    id: "usina-auditorio",
    sede: "Usina del Arte",
    nombre: "Auditorio",
    ubicacion: "Agustín F. Caffarena 1, CABA (Se acredita en Caffarena 29)",
    capacidad: 700,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Sonido e iluminación",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    contacto: "Victoria Barlaro +54 9 11 6676-9925",
    notas: "Estacionamiento en Caffarena 39",
  },
  {
    id: "usina-sala-camara",
    sede: "Usina del Arte",
    nombre: "Sala de Cámara",
    ubicacion: "Agustín F. Caffarena 1, CABA (Se acredita en Caffarena 29)",
    capacidad: 280,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Sonido e iluminación",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    notas: "Estacionamiento en Caffarena 39",
  },
  {
    id: "usina-salon-mayor-hall-central",
    sede: "Usina del Arte",
    nombre: "Salón Mayor y Hall Central",
    ubicacion: "Agustín F. Caffarena 1, CABA",
    capacidad: null,
    accesibilidad: true,
    tecnica: false,
    mobiliario: false,
    backstage: false,
    estacionamiento: null,
    wifi: false,
    sinFichaTecnica: true,
    notas: "Espacio mostrado en el PDF sin ficha de capacidad ni equipamiento",
  },
  {
    id: "usina-oficinas",
    sede: "Usina del Arte",
    nombre: "Oficinas",
    ubicacion: "Agustín F. Caffarena 1, CABA",
    capacidad: null,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Televisor (sala de reuniones)",
    mobiliario: true,
    backstage: false,
    estacionamiento: null,
    wifi: false,
    sinFichaTecnica: true,
    notas: "El PDF muestra una sala de reuniones con mesa, sillas y televisor. También muestra un espacio de estar con sillones",
  },

  // ========= UNICABA =========
  {
    id: "unicaba-auditorio",
    sede: "UNICABA",
    nombre: "Auditorio",
    ubicacion: "Av. Paseo Colón 255, CABA",
    capacidad: 100,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: true,
    wifi: false,
  },

  // ========= MDHyH =========
  {
    id: "mdhyh-sum",
    sede: "Ministerio de Desarrollo Humano y Hábitat",
    nombre: "SUM",
    ubicacion: "Av. Piedra Buena 3280, CABA",
    capacidad: 100,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantalla, proyector y sonido sin micrófonos",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
  },

  // ========= CMD (3) — solo eventos gaming =========
  {
    id: "cmd-auditorio",
    sede: "CMD",
    nombre: "Auditorio",
    ubicacion: "Algarrobo 1041, CABA",
    capacidad: 200,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantalla, proyector y sonido con micrófonos",
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
    restricciones: ["Solo eventos gaming"],
  },
  {
    id: "cmd-sala-barco",
    sede: "CMD",
    nombre: "Sala Barco",
    ubicacion: "Algarrobo 1041, CABA",
    capacidad: 70,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantalla, proyector y sonido con micrófonos",
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    contacto: "Debora +54 9 11 5018-7978",
    restricciones: ["Solo eventos gaming"],
    notas: "Accesibilidad con ascensor. Catering del lado de afuera",
  },
  {
    id: "cmd-espacios-generales",
    sede: "CMD",
    nombre: "Espacios generales",
    ubicacion: "Algarrobo 1041, CABA",
    capacidad: null,
    accesibilidad: true,
    tecnica: false,
    mobiliario: false,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    sinFichaTecnica: true,
    restricciones: ["Solo eventos gaming"],
    notas: "Espacios amplios mostrados en el PDF, sin ficha técnica adicional",
  },

  // ========= PLANETARIO =========
  {
    id: "planetario-auditorio",
    sede: "Planetario",
    nombre: "Auditorio",
    ubicacion: "Av. Sarmiento, CABA",
    capacidad: 250,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantalla",
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
  },

  // ========= CIFA =========
  {
    id: "cifa-auditorio",
    sede: "CIFA",
    nombre: "Auditorio",
    ubicacion: "Paseo Islas Malvinas. Av. Castañares, CABA",
    capacidad: 80,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantalla y televisor",
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: sillas, sillones y mesas",
  },

  // ========= TEMPLETE =========
  {
    id: "templete",
    sede: "Templete",
    nombre: "Templete",
    ubicacion: "Av. Caseros 3250, CABA",
    capacidad: 45,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantalla",
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
  },

  // ========= CUCICBA =========
  {
    id: "cucicba-salon",
    sede: "CUCICBA",
    nombre: "Salón",
    ubicacion: "Alsina 1382, CABA",
    capacidad: 200,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "pantalla, proyector, sonido y micrófonos",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
  },

  // ========= CASA DE LA LECTURA =========
  {
    id: "casa-lectura-sala",
    sede: "Casa de la Lectura",
    nombre: "Sala",
    ubicacion: "Lavalleja 924, CABA",
    capacidad: 80,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: true,
    estacionamiento: null,
    wifi: false,
  },

  // ========= BIBLIOTECA RICARDO GÜIRALDES =========
  {
    id: "biblioteca-guiraldes-sala",
    sede: "Biblioteca Ricardo Güiraldes",
    nombre: "Sala",
    ubicacion: "Talcahuano 1261, CABA",
    capacidad: 18,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
  },

  // ========= PARQUE DE LA ESTACIÓN =========
  {
    id: "parque-estacion-sum",
    sede: "Parque de la Estación",
    nombre: "SUM",
    ubicacion: "Tte. Gral. Juan Domingo Perón 3326, CABA",
    capacidad: 100,
    accesibilidad: true,
    tecnica: false,
    mobiliario: false,
    backstage: true,
    estacionamiento: false,
    wifi: false,
    notas: "Backstage al aire libre",
  },

  // ========= UNIVERSIDAD DE BELGRANO =========
  {
    id: "univ-belgrano-auditorio-roca",
    sede: "Universidad de Belgrano",
    nombre: "Auditorio Roca",
    ubicacion: "Zabala 1837, CABA",
    capacidad: 181,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Sonido, proyector, pantalla y micrófonos",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    notas: "Estacionamiento sin cargo",
  },

  // ========= FUNDACIÓN BEETHOVEN =========
  {
    id: "beethoven-auditorio",
    sede: "Fundación Beethoven",
    nombre: "Auditorio",
    ubicacion: "Av. Santa Fé 1452, CABA (Comuna 2)",
    capacidad: 263,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Sonido, pantalla, proyector e iluminación",
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: butaca",
  },

  // ========= CASA DE LA CULTURA =========
  {
    id: "casa-cultura-salon-dorado",
    sede: "Casa de la Cultura",
    nombre: "Salón Dorado",
    ubicacion: "Av. de Mayo 575, CABA",
    capacidad: 200,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "pantalla, sonido, micrófono, proyector",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
  },

  // ========= JARDÍN BOTÁNICO =========
  {
    id: "jardin-botanico-sum",
    sede: "Jardín Botánico",
    nombre: "SUM",
    ubicacion: "Av. Santa Fe 2951, CABA",
    capacidad: 40,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
  },

  // ========= MINISTERIO DE EDUCACIÓN =========
  {
    id: "min-educacion-auditorio",
    sede: "Ministerio de Educación",
    nombre: "Auditorio",
    ubicacion: "Carlos H. Perette 750, CABA",
    capacidad: 200,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Sonido, pantalla y proyector",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
  },

  // ========= CENTRO CULTURAL 25 DE MAYO (2) =========
  {
    id: "cc-25-mayo-teatro",
    sede: "Centro Cultural 25 de Mayo",
    nombre: "Teatro",
    ubicacion: "Av. Triunvirato 4444, CABA",
    capacidad: 450,
    accesibilidad: true,
    tecnica: true,
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: butacas",
  },
  {
    id: "cc-25-mayo-sala",
    sede: "Centro Cultural 25 de Mayo",
    nombre: "Sala",
    ubicacion: "Av. Triunvirato 4444, CABA",
    capacidad: 90,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
  },

  // ========= PARQUE DE LA CIUDAD =========
  {
    id: "parque-ciudad-techos-azules",
    sede: "Parque de la Ciudad",
    nombre: "Techos Azules",
    ubicacion: "Av. Fernández de la Cruz 4000, CABA",
    capacidad: 200,
    accesibilidad: true,
    tecnica: false,
    mobiliario: false,
    backstage: true,
    estacionamiento: true,
    wifi: false,
  },

  // ========= TEATRO SAN MARTÍN (2) =========
  {
    id: "teatro-san-martin-sala-casacuberta",
    sede: "Teatro San Martín",
    nombre: "Sala Casacuberta",
    ubicacion: "Av. Corrientes 1530, CABA",
    capacidad: 566,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Sonido, micrófono e iluminación",
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
    notas: "Hall para el catering. Mobiliario: butacas",
  },
  {
    id: "teatro-san-martin-sala-martin-coronado",
    sede: "Teatro San Martín",
    nombre: "Sala Martín Coronado",
    ubicacion: "Av. Corrientes 1530, CABA",
    capacidad: 940,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Sonido, micrófonos e iluminación",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    notas: "Hall para el armado de catering. Cochera con acceso para técnica. El montacarga lleva directo al escenario. Mobiliario: butacas",
  },

  // ========= TEATRO PRESIDENTE ALVEAR =========
  {
    id: "teatro-presidente-alvear",
    sede: "Teatro Presidente Alvear",
    nombre: "Teatro Presidente Alvear",
    ubicacion: "Av. Corrientes 1659, CABA",
    capacidad: 800,
    accesibilidad: false,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: butacas",
  },

  // ========= TEATRO REGIO =========
  {
    id: "teatro-regio",
    sede: "Teatro Regio",
    nombre: "Teatro Regio",
    ubicacion: "Av. Córdoba 6056, CABA",
    capacidad: 660,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: butacas",
  },

  // ========= TEATRO SARMIENTO =========
  {
    id: "teatro-sarmiento",
    sede: "Teatro Sarmiento",
    nombre: "Teatro Sarmiento",
    ubicacion: "Av. Sarmiento 2715, CABA",
    capacidad: 250,
    accesibilidad: false,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: butacas",
  },

  // ========= TEATRO DE LA RIBERA =========
  {
    id: "teatro-ribera",
    sede: "Teatro de la Ribera",
    nombre: "Teatro de la Ribera",
    ubicacion: "Av. Pedro de Mendoza 1821, CABA",
    capacidad: 643,
    accesibilidad: false,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: butacas",
  },

  // ========= CINE TEATRO EL PLATA =========
  {
    id: "cine-teatro-el-plata",
    sede: "Cine Teatro El Plata",
    nombre: "Cine Teatro El Plata",
    ubicacion: "Av. Juan Bautista Alberdi 5765, CABA",
    capacidad: 700,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: butacas",
  },

  // ========= PARQUE DE INNOVACIÓN (3) =========
  {
    id: "parque-innovacion-domo-chico",
    sede: "Parque de Innovación",
    nombre: "Domo Chico",
    ubicacion: "Av. Guillermo Udaondo, CABA",
    capacidad: 50,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
  },
  {
    id: "parque-innovacion-domo-intermedio",
    sede: "Parque de Innovación",
    nombre: "Domo Intermedio",
    ubicacion: "Av. Guillermo Udaondo, CABA",
    capacidad: 80,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    notas: "Salvo la Cúpula Grande",
  },
  {
    id: "parque-innovacion-domo-grande",
    sede: "Parque de Innovación",
    nombre: "Domo Grande",
    ubicacion: "Av. Guillermo Udaondo, CABA",
    capacidad: 100,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
  },

  // ========= MUSEO MODERNO (3) =========
  {
    id: "museo-moderno-auditorio",
    sede: "Museo Moderno",
    nombre: "Auditorio",
    ubicacion: "Av. San Juan 350, CABA",
    capacidad: 200,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "pantalla, proyector y sonido",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    escenario: false,
    notas: "Rampa y ascensor. Mobiliario: solo sillas",
  },
  {
    id: "museo-moderno-dinamica-mesas",
    sede: "Museo Moderno",
    nombre: "Dinámica de mesas",
    ubicacion: "Av. San Juan 350, CABA",
    capacidad: 100,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "pantalla, proyector y sonido",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    escenario: false,
    notas: "Rampa y ascensor. Mobiliario: solo sillas",
  },
  {
    id: "museo-moderno-sala-yapeyu",
    sede: "Museo Moderno",
    nombre: "Sala Yapeyú",
    ubicacion: "Av. San Juan 350, CABA",
    capacidad: 30,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "pantalla y proyector",
    mobiliario: true,
    backstage: true,
    estacionamiento: true,
    wifi: false,
    notas: "Rampa y ascensor. Mobiliario: sillas y mesa rectangular",
  },

  // ========= MUSEO LARRETA =========
  {
    id: "museo-larreta-sala",
    sede: "Museo Larreta",
    nombre: "Sala",
    ubicacion: "Av. Juramento 2291, CABA",
    capacidad: 80,
    accesibilidad: false,
    tecnica: false,
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
    notas: "Mobiliario: solo sillas",
  },

  // ========= MUSEO BAM (3) =========
  {
    id: "museo-bam-sala-principal",
    sede: "Museo BAM",
    nombre: "Sala Principal",
    ubicacion: "Defensa 223, CABA",
    capacidad: 50,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
  },
  {
    id: "museo-bam-sala-reuniones",
    sede: "Museo BAM",
    nombre: "Sala de reuniones",
    ubicacion: "Defensa 223, CABA",
    capacidad: null,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Televisor",
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    sinFichaTecnica: true,
    notas: "Sala con mesa, sillas y sillones",
  },
  {
    id: "museo-bam-terraza",
    sede: "Museo BAM",
    nombre: "Terraza",
    ubicacion: "Defensa 223, CABA",
    capacidad: null,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    sinFichaTecnica: true,
    notas: "Espacio exterior con mesas y sillas",
  },

  // ========= MUSEO SÍVORI (2) =========
  {
    id: "museo-sivori-espacio-exterior",
    sede: "Museo Sívori",
    nombre: "Espacio Exterior",
    ubicacion: "Av. Infanta Isabel 555, CABA",
    capacidad: null,
    accesibilidad: true,
    tecnica: false,
    mobiliario: false,
    backstage: false,
    estacionamiento: false,
    wifi: false,
  },
  {
    id: "museo-sivori-pasillos",
    sede: "Museo Sívori",
    nombre: "Pasillos",
    ubicacion: "Av. Infanta Isabel 555, CABA",
    capacidad: null,
    accesibilidad: true,
    tecnica: false,
    mobiliario: false,
    backstage: false,
    estacionamiento: false,
    wifi: false,
    sinFichaTecnica: true,
    notas: "Espacio interior mostrado en el PDF, sin ficha técnica adicional",
  },

  // ========= MUSEO FERNÁNDEZ BLANCO =========
  {
    id: "museo-fernandez-blanco-exterior",
    sede: "Museo Fernández Blanco",
    nombre: "Espacio exterior",
    ubicacion: "Suipacha 1422, CABA",
    capacidad: null,
    accesibilidad: true,
    tecnica: false,
    mobiliario: false,
    backstage: false,
    estacionamiento: false,
    wifi: false,
  },

  // ========= MUSEO POPULAR JOSÉ HERNÁNDEZ =========
  {
    id: "museo-jose-hernandez-exterior",
    sede: "Museo Popular José Hernández",
    nombre: "Espacio Exterior",
    ubicacion: "Av. del Libertador 2373, CABA",
    capacidad: null,
    accesibilidad: true,
    tecnica: false,
    mobiliario: false,
    backstage: false,
    estacionamiento: false,
    wifi: false,
  },

  // ========= MEZQUITA DE PALERMO =========
  {
    id: "mezquita-palermo",
    sede: "Mezquita de Palermo",
    nombre: "Mezquita de Palermo",
    ubicacion: "Av. Int. Bullrich 120, CABA",
    capacidad: null,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: true,
    wifi: false,
  },

  // ========= EXO =========
  {
    id: "exo-auditorio",
    sede: "EXO",
    nombre: "Auditorio",
    ubicacion: "Av. Chiclana 3444, CABA",
    capacidad: 50,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantalla, sonido",
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
  },

  // ========= AUDITORIO BELGRANO =========
  {
    id: "auditorio-belgrano",
    sede: "Auditorio Belgrano",
    nombre: "Auditorio Belgrano",
    ubicacion: "Virrey Loreto 2348, CABA",
    capacidad: 1200,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "luz y sonido",
    mobiliario: true,
    backstage: true,
    estacionamiento: false,
    wifi: false,
    notas: "Accesibilidad hasta el Foyer. Distribución: abajo 1000 / arriba 200. Mobiliario: butacas",
  },

  // ========= LEGISLATURA (5) =========
  {
    id: "legislatura-planta-principal",
    sede: "Legislatura de la Ciudad de Buenos Aires",
    nombre: "Legislatura de la Ciudad de Buenos Aires",
    ubicacion: "Perú 160, CABA",
    capacidad: 50,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantallas",
    mobiliario: true,
    backstage: false,
    estacionamiento: null,
    wifi: true,
    notas: "Jueves único día que no se puede usar por Sesión. Mobiliario: 50 sillas y 3 mesas",
  },
  {
    id: "legislatura-salon-dorado",
    sede: "Legislatura de la Ciudad de Buenos Aires",
    nombre: "Salón Dorado",
    ubicacion: "Perú 160, CABA",
    capacidad: 150,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantallas",
    mobiliario: true,
    backstage: false,
    estacionamiento: null,
    wifi: true,
    notas: "Jueves único día que no se puede usar por Sesión. Mobiliario: 150 sillas",
  },
  {
    id: "legislatura-salon-san-martin",
    sede: "Legislatura de la Ciudad de Buenos Aires",
    nombre: "Salón San Martín",
    ubicacion: "Perú 160, CABA",
    capacidad: 100,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantallas",
    mobiliario: true,
    backstage: false,
    estacionamiento: null,
    wifi: true,
    notas: "Jueves único día que no se puede usar por Sesión",
  },
  {
    id: "legislatura-salon-montevideo",
    sede: "Legislatura de la Ciudad de Buenos Aires",
    nombre: "Salón Montevideo",
    ubicacion: "Perú 160, CABA",
    capacidad: 80,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantallas y técnica",
    mobiliario: true,
    backstage: false,
    estacionamiento: null,
    wifi: true,
    notas: "Jueves único día que no se puede usar por Sesión",
  },
  {
    id: "legislatura-salon-eva-peron",
    sede: "Legislatura de la Ciudad de Buenos Aires",
    nombre: "Salón Eva Perón",
    ubicacion: "Perú 160, CABA",
    capacidad: 50,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantallas",
    mobiliario: true,
    backstage: false,
    estacionamiento: null,
    wifi: true,
    notas: "Jueves único día que no se puede usar por Sesión. Mobiliario: 50 sillas y 3 mesas",
  },

  // ========= IUDPT =========
  {
    id: "iudpt-auditorio",
    sede: "IUDPT",
    nombre: "Auditorio",
    ubicacion: "Sánchez de Loria 2364, CABA",
    capacidad: 100,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantallas, sonido, micrófonos",
    mobiliario: true,
    backstage: false,
    estacionamiento: null,
    wifi: true,
    notas: "Jueves único día que no se puede usar por Sesión",
  },

  // ========= SECRETARÍA DE INNOVACIÓN (4) =========
  {
    id: "sec-innovacion-sala-telon",
    sede: "Secretaría de Innovación",
    nombre: "Sala Telón",
    ubicacion: "Zavaleta 190, CABA",
    capacidad: 50,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantallas",
    mobiliario: true,
    backstage: false,
    estacionamiento: null,
    wifi: true,
    restricciones: [
      "Solo CAFE dentro de la sala, no se puede catering",
      "No acepta ingreso a menores de edad",
    ],
  },
  {
    id: "sec-innovacion-sala-moldeado",
    sede: "Secretaría de Innovación",
    nombre: "Sala Moldeado",
    ubicacion: "Zavaleta 190, CABA",
    capacidad: 10,
    accesibilidad: true,
    tecnica: false,
    mobiliario: true,
    backstage: false,
    estacionamiento: null,
    wifi: true,
    restricciones: [
      "Solo CAFE dentro de la sala, no se puede catering",
      "No acepta ingreso a menores de edad",
    ],
    notas: "Mobiliario: sillas y mesa",
  },
  {
    id: "sec-innovacion-sala-cincel",
    sede: "Secretaría de Innovación",
    nombre: "Sala Cincel",
    ubicacion: "Zavaleta 190, CABA",
    capacidad: 50,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantallas",
    mobiliario: true,
    backstage: false,
    estacionamiento: null,
    wifi: true,
    restricciones: [
      "Solo CAFE dentro de la sala, no se puede catering",
      "No acepta ingreso a menores de edad",
    ],
  },
  {
    id: "sec-innovacion-sala-escultural",
    sede: "Secretaría de Innovación",
    nombre: "Sala Escultural",
    ubicacion: "Zavaleta 190, CABA",
    capacidad: 16,
    accesibilidad: true,
    tecnica: true,
    tecnicaDetalle: "Pantallas",
    mobiliario: true,
    backstage: false,
    estacionamiento: null,
    wifi: true,
    restricciones: [
      "Solo CAFE dentro de la sala, no se puede catering",
      "No acepta ingreso a menores de edad",
    ],
    notas: "Mobiliario: sillas y mesa",
  },
];
